// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <Fl/Fl_Slider.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  inline void cb_DBG_i(Fl_Button*, void*);
  static void cb_DBG(Fl_Button*, void*);
  inline void cb_SM1_i(Fl_Button*, void*);
  static void cb_SM1(Fl_Button*, void*);
  inline void cb_SM2_i(Fl_Button*, void*);
  static void cb_SM2(Fl_Button*, void*);
  inline void cb_SM3_i(Fl_Button*, void*);
  static void cb_SM3(Fl_Button*, void*);
  inline void cb_TilingMode_i(Fl_Button*, void*);
  static void cb_TilingMode(Fl_Button*, void*);
  inline void cb_AMB_i(Fl_Slider*, void*);
  static void cb_AMB(Fl_Slider*, void*);
  inline void cb_SPEC_i(Fl_Slider*, void*);
  static void cb_SPEC(Fl_Slider*, void*);
  inline void cb_NewButton_i(Fl_Return_Button*, void*);
  static void cb_NewButton(Fl_Return_Button*, void*);
public:
  void show();
  void DBG_cb();
  void SM1_cb();
  void SM2_cb();
  void SM3_cb();
  void AMB_cb();
  void SPEC_cb();
  void TilingMode_cb();
  void NewButton_cb();
};
#endif
